services:
  flyway:
    build: .
    environment: 
      - DB_PASSWORD=${DB_PASSWORD}
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports: 
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}